USE [master]
GO

/****** Object:  Database [NimapInfotech]    Script Date: 10-03-2023 19:07:38 ******/
CREATE DATABASE [NimapInfotech]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Nimap Infotech', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Nimap Infotech.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Nimap Infotech_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Nimap Infotech_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NimapInfotech].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NimapInfotech] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NimapInfotech] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NimapInfotech] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NimapInfotech] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NimapInfotech] SET ARITHABORT OFF 
GO

ALTER DATABASE [NimapInfotech] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NimapInfotech] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NimapInfotech] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NimapInfotech] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NimapInfotech] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NimapInfotech] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NimapInfotech] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NimapInfotech] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NimapInfotech] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NimapInfotech] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NimapInfotech] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NimapInfotech] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NimapInfotech] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NimapInfotech] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NimapInfotech] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NimapInfotech] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NimapInfotech] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NimapInfotech] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NimapInfotech] SET  MULTI_USER 
GO

ALTER DATABASE [NimapInfotech] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NimapInfotech] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NimapInfotech] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NimapInfotech] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NimapInfotech] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NimapInfotech] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [NimapInfotech] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NimapInfotech] SET  READ_WRITE 
GO

